import storyblok_to_ts from "storyblok-generate-ts"
import { err, ok, type Result } from "neverthrow"

export async function generate_types({
  space_id,
  data,
}: {
  space_id: string
  data: unknown
}): Promise<Result<string, unknown>> {
  try {
    const generated = await storyblok_to_ts({
      componentsJson: data as never,
      path: `${space_id}.ts`,
      compilerOptions: {
        additionalProperties: false,
        unknownAny: true,
        style: {
          useTabs: true,
          singleQuote: true,
          trailingComma: "none",
          printWidth: 100,
        },
      },
    }).then((arr) => arr.join("\n"))

    const header =
      `
/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by the generate script on ${new Date().toISOString()}.
 * Any changes will be overwritten.
 */

import type { SbBlokData } from "@storyblok/svelte"

export type Blok<T> = SbBlokData & T
`.trim() + "\n\n"

    const ts =
      header +
      generated.replace(
        "import {StoryblokStory} from 'storyblok-generate-ts'",
        "import type { StoryblokStory } from 'storyblok-generate-ts'"
      )

    return ok(ts)
  } catch (e) {
    return err(e)
  }
}
